apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-cfahrni
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  - servicemonitor
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]