apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: kube-metrics
  name: kube-metrics
spec:
  endpoints:
    - interval: 60s
      port: https
      scheme: https
      path: /metrics
  selector:
    matchLabels:
      prometheus-monitoring: 'true'