{{- define "query.ingress" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.user }}-thanos
  name: {{ .Values.user }}-thanos
spec:
  rules:
  - host: {{ .Values.user }}-thanos-query.training.cluster.acend.ch
    http:
      paths:
      - backend:
          service:
            name: thanos-query
            port:
              number: 10902
        path: /
        pathType: ImplementationSpecific
{{- end }}