{{- define "alertmanager.alertmanager" }}
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.user }}-alertmanager
  name: {{ .Values.user }}-alertmanager
spec:
  alertmanagerConfigNamespaceSelector:
    matchLabels:
      user: {{ .Values.user }}-alertmanager
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: {{ .Values.user }}-alertmanager
  image: quay.io/prometheus/alertmanager:v0.25.0
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 40Mi
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 100Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    haproxy.org/auth-secret: basic-auth
    haproxy.org/auth-type: basic-auth
    haproxy.org/auth-realm: Authentication Required
  name: {{ .Values.user }}-alertmanager
spec:
  rules:
  - host: {{ .Values.user }}-alertmanager.training.cluster.acend.ch
    http:
      paths:
      - backend:
          service:
            name: alertmanager-operated
            port:
              number: 9093
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.user }}-alertmanager.training.cluster.acend.ch
    secretName: acend-wildcard
{{- end }}