{{- define "prometheus.prometheus" }}
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/name: prometheus
  name: prometheus
spec:
  {{- if .Values.query.enabled }}
  thanos:
    image: quay.io/thanos/thanos:v0.32.3
  {{- end }}
  scrapeInterval: 60s
  serviceAccountName: prometheus-{{ .Values.user }}
  serviceMonitorNamespaceSelector:
    matchLabels:
      user: {{ .Values.user }}
  serviceMonitorSelector: {}
  podMonitorNamespaceSelector:
    matchLabels:
      user: {{ .Values.user }}
  podMonitorSelector: {}
  probeNamespaceSelector:
    matchLabels:
      user: {{ .Values.user }}
  probeSelector: {}
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: true
  externalLabels:
    monitoring: {{ .Values.user }}
  securityContext:
    fsGroup: 65534
  storage:
    disableMountSubPath: true
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 10Gi
{{- end }}