---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cfahrni-prom-stack
  namespace: argocd
spec:
  destination:
    namespace: cfahrni-monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/cfahrni/prometheus-training-lab-setup'
    path: charts/user-monitoring/
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true