apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: node-exporter
  name: node-exporter
spec:
  endpoints:
    - interval: 60s
      port: node-exporter
      scheme: http
      path: /metrics
  selector:
    matchLabels:
      prometheus-monitoring: 'true'